### ISSUE TITLE
Cannot parse colour codes

### ISSUE THREAD

**Issue by bowser0000** [doej1367/MinecraftChatLogFilter#4]
The mod Patcher adds colour codes to logs, but this program uses a charset that doesn't support them. This also makes including colour codes in regex give 0 results.

E.x.: `§r§aYou salvaged a §r§9Shimmering Light Slippers§r§a!§r§7 (22)§r` shows as `�r�aYou salvaged a �r�9Shimmering Light Slippers�r�a!�r�7 (22)�r`.

Something helpful would be an option to automatically strip colour codes when searching.

**Comment by doej1367** [comment]
I got Patcher installed as well, but I can neither find an option for this nor does this happen to my chat logs. Are you shure it is patcher 1.8.0 doing this? I need to be able to reproduce this in order to test possible solutions.

**Comment by doej1367** [comment]
Think I fixed it and added the suggested option in [v1.0.4](https://github.com/doej1367/MinecraftChatLogFilter/releases/tag/1.0.4).
You should be able to either strip all text from color codes or even search for them as the "§" characters are decoded correctly now.

Feedback would be appreciated :)

EDIT: reopened as I don't know if you can reply to closed issues... just in case

**Comment by bowser0000** [comment]
Seems to be working perfectly, thanks for adding the option.

Also, after some testing, it seems the mod adding colour codes to logs was actually SkyblockAddons.
